///
/// This code has been auto-generated by LemonInc.Tools.Databases
///

using LemonInc.Core.Utilities;
using LemonInc.Tools.Databases.Models;
using System.Collections.Generic;
using System.Linq;
#if UNITY_EDITOR
using UnityEditor;
#endif
using UnityEngine;

namespace Databases
{
	public class RuntimeDatabase : Singleton<RuntimeDatabase>
{
private DatabaseData _data;
#if UNITY_EDITOR
public DatabaseData RuntimeDatabaseData => _data ??= AssetDatabase.LoadAllAssetsAtPath("Assets/Game/Resources/Runtime.asset").FirstOrDefault() as DatabaseData;
#else
public DatabaseData RuntimeDatabaseData => _data ??= Resources.Load<DatabaseData>("Runtime");
#endif
public static class Data
{
public static Game.Entities.Player.PlayerStatData PlayerData = (Game.Entities.Player.PlayerStatData)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["ae9f60c8-bb58-4ed4-8926-0646c0279b0f"].Data;
public static UnityEngine.GameObject OnFireFx = (UnityEngine.GameObject)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["45c381f1-0a29-4d68-9067-fb5a01f3b4e1"].Data;
public static Game.Systems.Audio.AudioData Audio = (Game.Systems.Audio.AudioData)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["18bbdfa4-a50b-4fd9-863e-070dd019f119"].Data;

/// <summary>
/// Gets all assets from this section.
/// </summary>
/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
public static IEnumerable<T> All<T>()
   where T : UnityEngine.Object
{
   var all = new UnityEngine.Object[3] { PlayerData, OnFireFx, Audio };
   return all.OfType<T>();
}
}

public static class NpcSkins
{
public static UnityEngine.Object A = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["6fcf2265-6df1-491b-85b3-8b2798e29cec"].Data;
public static UnityEngine.Object B = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["4c90ef8a-0aa5-4d60-93d0-b77950fb9de2"].Data;
public static UnityEngine.Object C = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["0f77380e-cde4-44de-a29f-f094069ade38"].Data;
public static UnityEngine.Object D = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["7732ed6c-4777-4830-a189-ce27552e4b0a"].Data;
public static UnityEngine.Object E = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["1ebea4e0-5c77-4775-85c7-7c7dd94f6484"].Data;
public static UnityEngine.Object F = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["c8b12209-5d15-413a-a2a5-d775a7a1ff37"].Data;
public static UnityEngine.Object G = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["dee7f0be-8fa2-4cd3-9a2c-341de2e194ba"].Data;
public static UnityEngine.Object H = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["f0ca194a-ff9d-48e7-b8e1-15bbc2d0d471"].Data;
public static UnityEngine.Object I = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["92379240-8717-4a3c-99d0-620f194f0e20"].Data;
public static UnityEngine.Object J = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["288424b8-d30d-4128-a0cf-9bf8964d1908"].Data;
public static UnityEngine.Object K = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["beeb31d0-15a9-40aa-ae6a-1645e8f43fa2"].Data;
public static UnityEngine.Object L = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["ee12d71e-f575-4a30-9b22-facc2def39db"].Data;

/// <summary>
/// Gets all assets from this section.
/// </summary>
/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
public static IEnumerable<T> All<T>()
   where T : UnityEngine.Object
{
   var all = new UnityEngine.Object[12] { A, B, C, D, E, F, G, H, I, J, K, L };
   return all.OfType<T>();
}
}

public static class WheelChairs
{
public static UnityEngine.Object Deluxe = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["74f63e79-524e-46d0-8156-ab03e6f697eb"].Data;
public static UnityEngine.Object Bbb = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["74cbbfb9-9f51-4a43-b0f5-2224725330d7"].Data;
public static UnityEngine.Object Power = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["cb435812-97cf-4aed-9181-20d646360787"].Data;
public static UnityEngine.Object Basic = (UnityEngine.Object)RuntimeDatabase.Instance.RuntimeDatabaseData.AssetDefinitions["c088d11e-bc02-4133-8945-5fa26a78a7d6"].Data;

/// <summary>
/// Gets all assets from this section.
/// </summary>
/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
public static IEnumerable<T> All<T>()
   where T : UnityEngine.Object
{
   var all = new UnityEngine.Object[4] { Deluxe, Bbb, Power, Basic };
   return all.OfType<T>();
}
}

}


}

